### ISSUE TITLE
添加检测root权限

### ISSUE THREAD

**Issue by obeta** [mghcool/Raspberry-backup#1]
2个问题
1.普通账号是否能完整备份全部数据，如果不能为何不添加检测root权限

2.安装宝塔后备份IMG提示错误（用的root权限，也有可能我的问题）

复制文件到img...
备份分区 /dev/boot
备份boot完成
备份分区 /dev/root
  5,070,412,455  95%   16.87MB/s    0:04:46 (xfr#46986, to-chk=12195/71564)
rsync: [sender] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(823) [sender=3.2.3]
rsync error: received SIGUSR1 (code 19) at main.c(1595) [generator=3.2.3]
root@raspberrypi:/home/ly# rsync: [sender] write error: Broken pipe (32)
rsync: [sender] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(823) [sender=3.2.3]
rsync error: received SIGUSR1 (code 19) at main.c(1595) [generator=3.2.3]
rsync: [sender] write error: Broken pipe (32)
bash: 未预期的符号“(”附近有语法错误
bash: 未预期的符号“(”附近有语法错误
bash: 未预期的符号“(”附近有语法错误
bash: 未预期的符号“(”附近有语法错误
bash: 未预期的符号“(”附近有语法错误

**Comment by mghcool** [comment]
1、普通账号不具备一些重要目录的权限，所以没法使用普通权限备份，如果使用普通用户，可以在脚本前加上 `sudo`
2、请说明一下宝塔的版本信息
